### ISSUE TITLE
result of the model checkpoint (seq of toys)

### ISSUE THREAD

**Issue by linglingl635** [WangXFng/ELMRec#1]
the model on the google drive doesn't match the result in the paper. so could you upadte the model checkpoint on the google drive?
the result I test is (seq of toys)
![image](https://github.com/user-attachments/assets/f9a866bf-0697-4be3-ba00-4ed99b439834)

**Comment by WangXFng** [comment]
Thank you for your reminding. I will check it and update.

**Comment by WangXFng** [comment]
Indeed! It is not the correct one. I have already uploaded my copy. Thank you again!
You can see the result as follows:
![image](https://github.com/user-attachments/assets/e637e31e-bc56-4614-adc9-92981d9af6d1)

**Comment by linglingl635** [comment]
thanks for that, its helps a lot
