### ISSUE TITLE
question about alpha

### ISSUE THREAD

**Issue by linglingl635** [WangXFng/ELMRec#3]
the value of alpha in the code doesn’t match the result in fig 5 in the paper
Can you fix it ？

**Comment by WangXFng** [comment]
There are some fluctuations, i.e., sometimes other parameters work better than the one I reported. 
But the thing is, I conducted many times and reported the average results to show the variance trend. Please try it several times. 

Alternatively, you can report the results based on your own environment in your paper. 

Also, if you cannot obtain the results as shown in the paper, let me know which task and which dataset you are using. Thank you!

**Comment by linglingl635** [comment]
Sorry for the misunderstanding caused by my statement.  What I mean is that results in figure 5 and code in pretrain.py on line 37, are the values of sports and toys confused? 
for seq of toys alpha should be 9 and for seq of sports alpha should be 1 accoring to figure 5
So I think you should modify the code to match the results in Figure 5 of the paper. By the way, in the paper, the results of alpha in Table 9 and Figure 5 are inconsistent. I think you made an error in organizing the final results.

**Comment by WangXFng** [comment]
I see. I will check whether the code or the fig is incorrect. If necessary, I will release a new version via Arxiv.
Thank you again for your reminder!

**Comment by WangXFng** [comment]
I have checked the contents carefully. I found that the results in fig 5 are correct. I have revised table 9 and the related descriptions of the code. I will release a new version via Arxiv. 

Thank you once again for your reminder.
